/* config.h. Generated by cmake from config.h.cmake */

#cmakedefine KNEMO_VERSION "${KNEMO_VERSION}"
#cmakedefine PATH_IFCONFIG "${PATH_IFCONFIG}"
#cmakedefine PATH_IWCONFIG "${PATH_IWCONFIG}"
#cmakedefine PATH_IWLIST   "${PATH_IWLIST}"
#cmakedefine PATH_ROUTE    "${PATH_ROUTE}"
#cmakedefine HAVE_LIBIW 1
#cmakedefine USE_KNOTIFICATIONITEM 1
